  # Configuración del Proyecto
  project:
    type: book

  # Configuración de la Ejecución
  execute:
    freeze: auto

  # Metadatos del Libro
  book:
    title: "iabookMaquiloca"
    author: "Javier Flores"
    date: today
    downloads: ["pdf"]
    url: "https://xavierflore.com.mx/iabookMaquiloca"
    reader-mode: true
    description: "iabookMaquiloca"
    language: es
    sidebar:
      style: docked
      background: light
    search: true
    repo-url: "https://github.com/javierflores/iabookMaquiloca"
    sharing: ['facebook', 'twitter', 'linkedin']
    chapters:
      - index.qmd
      - intro.qmd
      - 01-fundamentos.qmd
      - 02-industria-maquiladora.qmd
      - 03-aplicaciones-ia.qmd
      - 05-empresa-lista.qmd
      - 06-futuro-ia.qmd
      - 07-conclusiones-recomendaciones.qmd
      - summary.qmd
      - references.qmd
  bibliography: references.bib
  d2:
        format: svg
        embed_mode: raw

  # Formatos de Salida
  format:
    bookup-html:
      toc: true
      filters:
        - d2
      d2:
        format: svg
        embed_mode: raw
    epub: 
      toc: true
      toc-depth: 3
      fontsize: 1rem
      linkcolor: highlight
      urlcolor: highlight
      filters:
        - d2
    pdf:
      title: joto
      pdf-engine: lualatex
      pdf-engine-opts:
          - '--no-shell-escape'
          - '--halt-on-error'
      toc: true
      toc-depth: 3
      colorlinks: true
      documentclass: book
      linkcolor: highlight
      urlcolor: highlight
      keep-tex: true
      latex-output-dir: _book
      fontsize: 10pt
      geometry: [a5paper, top=2.5cm, bottom=1cm, left=1cm, right=1cm]
      filters:
        - d2
      include-in-header:
        - |
          % Cargar fuentes y paquetes de estilo
          \usepackage{fontspec}
          \usepackage{emoji}
          \setmainfont{EB Garamond}        
          \usepackage{xcolor}
          \definecolor{highlight}{RGB}{29, 120, 200} 

          % Paquetes para tablas responsivas
          \usepackage{graphicx}     % Para \resizebox
          \usepackage{tabularx}     % Para tablas de ancho adaptable
          \usepackage[raggedrightboxes]{ragged2e} 

          % Paquete para soporte de idiomas
          \usepackage{polyglossia}
          \setmainlanguage{spanish} 

          % Microtipografía avanzada
          \usepackage[activate={true,nocompatibility},final,tracking=true,kerning=true,spacing=true,factor=1100,stretch=10,shrink=10]{microtype}

          \widowpenalty=10000
          \clubpenalty=10000

          % Control de ríos (ligeramente ragged right)
          \usepackage[raggedrightboxes]{ragged2e}

          % Gestión de guiones
          \hyphenpenalty=50 
          \exhyphenpenalty=50 
          \emergencystretch=3em

          % Paquete para la personalización del título
          \usepackage{titling}

          % Configuración de encabezados y pies de página
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \fancyhead[LE,RO]{\thepage} 
          \fancyhead[RE]{\nouppercase{\leftmark}} 
          \fancyhead[LO]{\nouppercase{\rightmark}}   
    
          \fancyfoot[C]{\thepage}

      include-before-body:
        - |
            \begin{document}

      include-after-body:
        - |
            \end{document}
      footer-includes:
        - |
            \fancyfoot[C]{\thepage}

      include-after:
        - |
            \backmatter
            \printbibliography



